import type { Collection } from "./types"

export const initialCollections: Collection[] = [
  {
    id: 1,
    name: "Combat Enhancement",
    description: "Essential mods for realistic combat experience",
    mods: [
      {
        id: 1,
        name: "@ACE3",
        version: "3.16.1",
        size: "1.2 GB",
        type: "mod",
        isServerMod: false,
        hasUpdate: false,
        disabled: false,
      },
      {
        id: 2,
        name: "CBA_A3",
        version: "3.15.8",
        size: "45 MB",
        type: "mod",
        isServerMod: false,
        hasUpdate: true,
        disabled: false,
      },
      {
        id: 3,
        name: "@TFAR",
        version: "1.0.328",
        size: "89 MB",
        type: "mod",
        isServerMod: false,
        hasUpdate: false,
        disabled: true,
      },
    ],
    createdAt: "2024-01-15",
    isActive: true,
  },
  {
    id: 2,
    name: "Vehicle Pack",
    description: "Additional vehicles and equipment",
    mods: [
      {
        id: 4,
        name: "RHS AFRF",
        version: "0.5.6",
        size: "2.8 GB",
        type: "mod",
        isServerMod: false,
        hasUpdate: false,
        disabled: false,
      },
      {
        id: 5,
        name: "RHS USAF",
        version: "0.5.6",
        size: "3.1 GB",
        type: "mod",
        isServerMod: false,
        hasUpdate: false,
        disabled: false,
      },
    ],
    createdAt: "2024-01-10",
    isActive: false,
  },
]
