version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: arma_server_manager_backend
    environment:
      - FLASK_ENV=development
      - DEV_DATABASE_URI=sqlite:///dev.db
      - SECRET_KEY=dev-secret
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./backend/temp:/app/temp
    networks:
      - arma_server_manager
    depends_on:
      - redis

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: arma_server_manager_frontend
    environment:
      - VITE_API_PROXY_TARGET=http://backend:5000
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - arma_server_manager
  redis:
    image: redis:7-alpine
    container_name: arma_server_manager_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - arma_server_manager

volumes:
  redis_data:
    driver: local

networks:
  arma_server_manager:
    driver: bridge
