/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServerConfigsRouteImport } from './routes/server-configs'
import { Route as SchedulesRouteImport } from './routes/schedules'
import { Route as ModSubscriptionsRouteImport } from './routes/mod-subscriptions'
import { Route as ControlPanelRouteImport } from './routes/control-panel'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as CollectionsCollectionIdRouteImport } from './routes/collections/$collectionId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerConfigsRoute = ServerConfigsRouteImport.update({
  id: '/server-configs',
  path: '/server-configs',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesRoute = SchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const ModSubscriptionsRoute = ModSubscriptionsRouteImport.update({
  id: '/mod-subscriptions',
  path: '/mod-subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlPanelRoute = ControlPanelRouteImport.update({
  id: '/control-panel',
  path: '/control-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCollectionIdRoute = CollectionsCollectionIdRouteImport.update({
  id: '/collections/$collectionId',
  path: '/collections/$collectionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/control-panel': typeof ControlPanelRoute
  '/mod-subscriptions': typeof ModSubscriptionsRoute
  '/schedules': typeof SchedulesRoute
  '/server-configs': typeof ServerConfigsRoute
  '/settings': typeof SettingsRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/collections': typeof CollectionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/control-panel': typeof ControlPanelRoute
  '/mod-subscriptions': typeof ModSubscriptionsRoute
  '/schedules': typeof SchedulesRoute
  '/server-configs': typeof ServerConfigsRoute
  '/settings': typeof SettingsRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/collections': typeof CollectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/control-panel': typeof ControlPanelRoute
  '/mod-subscriptions': typeof ModSubscriptionsRoute
  '/schedules': typeof SchedulesRoute
  '/server-configs': typeof ServerConfigsRoute
  '/settings': typeof SettingsRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/collections/': typeof CollectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/control-panel'
    | '/mod-subscriptions'
    | '/schedules'
    | '/server-configs'
    | '/settings'
    | '/collections/$collectionId'
    | '/collections'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/control-panel'
    | '/mod-subscriptions'
    | '/schedules'
    | '/server-configs'
    | '/settings'
    | '/collections/$collectionId'
    | '/collections'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/control-panel'
    | '/mod-subscriptions'
    | '/schedules'
    | '/server-configs'
    | '/settings'
    | '/collections/$collectionId'
    | '/collections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ControlPanelRoute: typeof ControlPanelRoute
  ModSubscriptionsRoute: typeof ModSubscriptionsRoute
  SchedulesRoute: typeof SchedulesRoute
  ServerConfigsRoute: typeof ServerConfigsRoute
  SettingsRoute: typeof SettingsRoute
  CollectionsCollectionIdRoute: typeof CollectionsCollectionIdRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-configs': {
      id: '/server-configs'
      path: '/server-configs'
      fullPath: '/server-configs'
      preLoaderRoute: typeof ServerConfigsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules': {
      id: '/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof SchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mod-subscriptions': {
      id: '/mod-subscriptions'
      path: '/mod-subscriptions'
      fullPath: '/mod-subscriptions'
      preLoaderRoute: typeof ModSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-panel': {
      id: '/control-panel'
      path: '/control-panel'
      fullPath: '/control-panel'
      preLoaderRoute: typeof ControlPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collectionId': {
      id: '/collections/$collectionId'
      path: '/collections/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof CollectionsCollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ControlPanelRoute: ControlPanelRoute,
  ModSubscriptionsRoute: ModSubscriptionsRoute,
  SchedulesRoute: SchedulesRoute,
  ServerConfigsRoute: ServerConfigsRoute,
  SettingsRoute: SettingsRoute,
  CollectionsCollectionIdRoute: CollectionsCollectionIdRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
